version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:5001"
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"